### ISSUE TITLE
"config.json file is missing"

### ISSUE THREAD

**Issue by nickshepherd1983** [auth0/auth0-dotnet-templates#22]
Hello,

Firstly, thank you for all the work you have done building out the Templates and the CLI; they make the life of me and my development team much better.

I gave your instructions a try today, but I ran into a small snag, and I'm hoping you'll be able to help out.

When I run "dotnet new auth0blazorserver -o MyBlazorServerApp" from powershell I recive the folllowing exeption

```
>dotnet registration/cli-wrapper.dll
Auth0 CLI is installed.
ERROR: ************

=== error

Γû╕ config.json file is missing

*******************
ERROR: ************
The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0.

Registration output: -------

*******************
Auth0 domain:
Client ID:
Audience:
Unhandled exception. System.Exception:
=== error

Γû╕ config.json file is missing

at CliWrapper.RunCommand(String command, String args) in /Users/andreachiarelli/Documents/Git/auth0-dotnet-templates/cli-wrapper/CliWrapper.cs:line 181
at CliWrapper.GetCurrentDomain() in /Users/andreachiarelli/Documents/Git/auth0-dotnet-templates/cli-wrapper/CliWrapper.cs:line 240
at CliWrapper.GetCurrentDomain(RegistrationData registrationData) in /Users/andreachiarelli/Documents/Git/auth0-dotnet-templates/cli-wrapper/CliWrapper.cs:line 229
at CliWrapper.UpdateConfigFiles(RegistrationData registrationData) in /Users/andreachiarelli/Documents/Git/auth0-dotnet-templates/cli-wrapper/CliWrapper.cs:line 101
at Program.<main>$(String[] args) in /Users/andreachiarelli/Documents/Git/auth0-dotnet-templates/cli-wrapper/Program.cs:line 13
at Program.<main>(String[] args)
Command failed.

Post action failed.
Manual instructions: Run './register-with-auth0.cmd'
Actual command: register-with-auth0.cmd


For details on the exit code, refer to https://aka.ms/templating-exit-codes#105
```

I have the latest CLI installed and I am able to use it if I login my session.

Any ideas?

**Comment by Kerpackie** [comment]
Can confirm I am encountering the same issue.

Using Latest CLI Version installed via scoop, and it is happening with all template types.

**Comment by andychiare** [comment]
Hey @Kerpackie,
I think this is an issue with the Auth0 CLI installation.
You should check if the `PATH` environment variable includes the folder containing your Auth0 CLI executable, and if the `HOME` environment variable exists and its value is the path to the path to your Auth0 CLI executable as well.

Check out [this thread](https://disqus.com/home/discussion/auth0blog/auth0_templates_for_net_a_new_powerful_version_released/) for more details.

**Comment by andychiare** [comment]
A [PR on the Auth0 CLI documentation](https://github.com/auth0/auth0-cli/pull/941) is open.

**Comment by andychiare** [comment]
[Manual installation instructions](https://github.com/auth0/auth0-cli?tab=readme-ov-file#manual) updated in the Auth0 CLI docs.
